branches:
  only:
    - development

language: android
sudo: false

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
   - pwd
 # - cd cloudboost-android-sdk 
  #- chmod u+x .travis/deploy.sh
before_install:
   - git config --global user.email "egimaben@gmail.com"
   - git config --global user.name "egimaben"
   - git config --global user.password "soulsurvivor1"
   - git config --global push.default simple
after_success:
   - git config credential.helper "store --file=.git/credentials"
   - echo "https://${MY_TOKEN}:@github.com" > .git/credentials
   - git add -A .
   - git commit -m 'tested build from travis'
   - git remote -v
   - git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git
   - git push
#before_deploy:
#   - cd $TRAVIS_BUILD_DIR
#   - chmod u+x deploy.sh
#deploy:
#  provider: script
#  script: deploy.sh
#  on:
#    branch: development

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
env:
  global:
   secure: s081zTfvJ38F5Md7stMjLuXjwVLfp73wFCPcqh3tWr67a2LDjjuaznYCZxq+s9PYPVZNER72MT5AmmodcfVjQavP8sWbDjR+2NWz/7hEEKWgZuCz7GAt8vIyWhd+vfV7mbe/U7Q48MQIlrPtG3nkLUUh7dASJHS0QagBYW4CYtp5MOWjtoJ/hKsgkSbwGUM/q5Lwsdzvo294L3nKmfu/tiRvgreORz4lpXlhtoKnHV5CRL8qqkRaqP1+6Gka0FERxL9gKRch3ddKcIRiG26l0ji+mdt8n5VYh4yH705smiEHCRTfmWnq5gm3xouB4yG4zu9Q5INn85nVZrkxfoJKUFiClLI3r6btOcdaIgcLMPH3GZ6ZQgzjjvwxM4s223tPZLwXIIoleY+irhElKUuPRjHUpYIlGSu+8G3oLrg2piPfUVELvw7aFGLPjnfb4Rv1f4+Q49RABXRxrWArsaao8nj9WG15mvnkwTtJ5uZuuoT7m6H0/B8gbt3OxdbZaY8TQEAQHBhIDRSF6gnRbWtZKu/1Un6yWnmcGOt41uzlxSeFZUglsGwPgPCegnowrVZ4Ubti73mEMzcmpbB7Zmchhhxy/Nycmbua6MG2WT/0oSDDMJzl2YIwIOXjyisoY4W5Dawvz2rUrV2i/QWFkrojTBW0SJY6RHmwakKUdP0sqwA=
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
	
