branches:
  only:
    - development

language: android
sudo: false

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
   - pwd
 # - cd cloudboost-android-sdk 
  # - chmod u+x .travis/deploy.sh
before_install:
   - git config --global user.email "egimaben@gmail.com"
   - git config --global user.name "egimaben"
   - git config --global user.password "${MY_TOKEN}"
   - git config --global push.default simple
after_success:
   - git clone https://egimaben:$MY_TOKEN@github.com/egimaben/JavaSDK.git --branch=development out
   - cd out
   - git checkout development
   - git remote rm origin
   - git remote add origin https://egimaben:$MY_TOKEN@github.com/egimaben/JavaSDK.git
   - echo "am just trying to make changes to push">text.txt
   - git config credential.helper "store --file=.git/credentials"
   - echo "https://${MY_TOKEN}:@github.com" > .git/credentials
   - git config user.name "egimaben"
   - git add -A .
   - git commit -m 'testing travis deploy script'
   - git remote -v
   - git push origin development
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/   
env:
  global:
  - secure: IfC3cLaWnJKZbn2PY+9h2rrkjD6WAnu/CLQk7/y0RaB24fuvM7n/g3GA5VoxZHVgxOV91rF2HbC2DE51JCGWIoo8s5pS1Xlq9K5WFxUfB0KMS5LVhY6TYhWwdtWUPuAgVmJUkbDnBLXX1psHaTA0EANBDw2TDWmMS4CuWMNUVt6Ss81qqHBWFlHV49JQ9otXP7SaeMHnwQx638vXdC/4G3w7+8HczQsXuShynPtgUnYl4ZTa/zvRZWWOx2jgz3W7zCYsRWLTOozfzlC/Q/PQafPdkcwyEuoPOxImibwT36F39f+AvVX6Jmi5Tz5JXXoZj5wZFI0EeYLNbmCO1ZWvzKLye2IYbSrHbldvIV1KT0eKynS+yIEMSt6kklELj9opr9C9Wg807YteDYUxiQOXrjkUkCv+nU0hdumy8r2Ldok6OkELDz+tU4KqsufZT/KFgtJLzNlCcuVqz6AiTzeDWFrC54h+GeGMGpKK/NokIfyqzh2J0q4t//7rFvr7pmgC3i1jJLt3jbvxGbek4sCKFBUZ/629OZsaC/3BfPaVa5MwTRU+8zecNd3+5FJMW1bdzaabQZP4Nr6suPryUktR9HuUHLjEJaNBTTMRY9zyWLMDogY8k+HYelJq4hJd4ZgkNX+o2aYlAJqKGv1wkRUrJv8R/AEosKRBqtkl8SdpmUQ=
