branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
  -- chmod +x gradlew
  - ./gradlew bintrayUpload --info

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
