branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
   - pwd
 # - cd cloudboost-android-sdk 
  #- chmod u+x .travis/deploy.sh
before_install:
   - git config --global user.email "egimaben@gmail.com"
   - git config --global user.name "egimaben"
   - git config --global user.password "soulsurvivor1"
   - git config --global push.default simple
   - git checkout master
after_success:
   - git add -A .
   - git commit -m 'tested build from travis'
   - git push origin master
before_deploy:
   - cd $TRAVIS_BUILD_DIR
   - chmod u+x deploy.sh
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
