branches:
  only:
    - development

language: android
sudo: false

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
  - cd cloudboost-android-sdk 
  
after_success:
  - cd ..
  - pwd
  - set -o errexit -o nounset
  - git config user.name "egimaben"
  - git config user.email "egimaben@gmail.com"
  - git config user.password "soulsurvivor1"
  - git add .
  - git commit -m "travis commit"
  - git push origin master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
